version: "3.8"
services:
  # apitesting:
  #   image: koti21/apisyniq_testing:v1.0.0
  #   container_name: apitesting
  #   build:
  #     context: ./Java_Agent
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #     - "7320:7320"
  #   env_file:
  #     - ./Java_Agent/.env
  #   depends_on:
  #     - postgres
  #     # - ollama
  #   networks:
  #     - apis


  apiresolver:
    image: koti21/apiresolver:v1.0.0
    container_name: apiresolver
    build:
      context: ./ApiResolver
      dockerfile: Dockerfile
    ports:
      - "7321:7321"
      - "7322:7322"
    env_file:
      - ./ApiResolver/.env
    depends_on:
      - postgres
      # - ollama
    networks:
      - apis
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: pg_vector
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - apis
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   entrypoint: >
  #       /bin/sh -c '
  #       for m in nomic-embed-text tinydolphin; do
  #         if [ ! -f "/root/.ollama/models/manifests/$m" ]; then
  #           echo "Pulling missing model: $m";
  #           ollama pull "$m";
  #         else
  #           echo "Model already exists: $m";
  #         fi;
  #       done;
  #       exec ollama serve'
  #   networks:
  #     - apis
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:11435/api/health" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10

volumes:
  db_data:
  # ollama_data:

networks:
  apis:
    driver: bridge