grpc:
    server:
        port: 7322
        enable-reflection: true
server:
  address: 0.0.0.0
  port: 7321

spring:
  import:
    optional:
      file: .env[.properties]
  application:
    name: ApiResolver
  ai:
    ollama:
      base-url: ${OLLAMA_SERVER:http://localhost:11434}
      init:
        pull-model-strategy: when_missing
        timeout: ${TIME_OUT:10000}
      chat:
        options:
          model: ${CHAT_MODEL:tinydolphin}
      embedding:
        options:
           model: ${EMBEDDINGS_MODEL:nomic-embed-text}
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        index-type: hnsw
        schema-validation: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/spring}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:koti21}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${HIBERNATE_AUTO:update}